server:
  port: 16000

spring:
  application:
    name: consumer

eureka:
  client:
    serviceUrl:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/"
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

logging:
  level:
    org:
      springframework:
        web: DEBUG·
        http: DEBUG

resilience4j:
  timelimiter:
    configs:
      default:
        timeoutDuration:
          nanos: 1
        cancelRunningFuture: true

    instances:
      backendA:
        baseConfig: default
